### ISSUE TITLE
v0.3.2 - Reorganize Assets

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Widgets#156]
### Reorganize Assets

- [x] #163 - kidoju.widgets.assetmanager: remove delete button when tab 0 is not the project tab

### Miscellaneous

- [x] #160 - Error: <rect> attribute width: A negative value is not valid. ("-8")
- [x] #162 - TypeError: `color` is expected to have type `string`
