### ISSUE TITLE
v0.3.3 - Improved Categories

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Widgets#161]
### Improved Categories

- N/A

### Miscellaneous

- [x] #96 kidoju.widgets.multiinput: cannot be used with kendoValidator
- [x] #169 - kidoju.tools: svg images raise error in diagnostics console
- [x] #174 - kidoju.widgets.styleeditor: set row in edit mode after clicking `New Style`

### Compare

https://github.com/kidoju/Kidoju-Widgets/compare/v0.3.2...v0.3.3
