### ISSUE TITLE
v0.3.4 - Add MathInput to Kidoju-WebApp and Kidoju-Mobile

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Widgets#186]
### Add MathInput to Kidoju-WebApp and Kidoju-Mobile

- [x] #133 - kidoju.widgets.mathinput: math formula editor
- [x] #181 - kidoju.widgets.mathinput: mvvm issue when deleting last char

### Miscellaneous

- [x] #44 - kidoju.widgets.styleeditor: add custom editors on values
- [x] #175 - kidoju.widgets.listeditor: fix tooltip positioning
- [x] #198 - https://github.com/kidoju/Kidoju-Widgets/issues/198
- [x] #199 - kidoju.widgets.codeeditor: Fix value binding
- [x] #200 - kidoju.widgets.propertygrid: remove handle positioning on MOUSEENTER

### Compare

https://github.com/kidoju/Kidoju-Widgets/compare/v0.3.3...v0.3.4
