### ISSUE TITLE
v0.3.5 - Release Kendo-Mobile for app store approval (before public release)

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Widgets#187]
### Release Kendo-Mobile for app store approval (before public release)

- N/A

### Miscellaneous

- [x] #159 - kidoju.widgets.assetmanager: query images from Wikipedia and google
- [x] #164 - kidoju.widgets.assetmanager: remove options.transport and options.default and simply handle as another collection with transport.create and transport.destroy in addition to transport.read
- [x] #176 - kidoju.widgets.markdown: introduce schemes for images
- [x] #206 - kidoju.widgets.markdown: add (tw)emojis
- [x] #207 - kidoju.widgets.mathinput: merge lowergreen and uppergreek into one single greek 
- [x] #210 - kidoju.widgets.splitbutton: implement a split button widget
- [x] #213 - kidoju.widgets.vectordrawing: add JPEG export (save as)
- [x] #214 - kidoju.widgets.vectordrawing: add PNG compression
- [x] #222 - kidoju.widgets.assetmanager: Remove flickering effect when changing tabs

### Compare

https://github.com/kidoju/Kidoju-Widgets/compare/v0.3.4...v0.3.5
