### ISSUE TITLE
v0.3.7 - Release first Mobile Apps  

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Widgets#220]
### Release first Mobile Apps

- [ ] TODO

### Miscellaneous

- [x] #166 - kidoju.widgets.connector: remove container (TBC)
- [x] #167 - kidoju.widgets.selector: remove container (TBC)
- [x] #170 - kidoju.widgets.dropzone: drop zones should allow omissions (or have an empty value)
- [x] #172 - kidoju.widgets.dropzone: drop zones should count draggables in place on init
- [x] #228 - kidoju.widgets.selector: redesign
- [x] #230 - kidoju.widgets.highlighter: new widget
- [x] #231 - kidoju.widgets.textgaps: fill text gaps with values

### Compare

https://github.com/kidoju/Kidoju-Widgets/compare/v0.3.6...v0.3.7
